### PR TITLE
Delete executable flags from non executable files

### PR DESCRIPTION
**Pull request by blogdron**
For resolve this https://github.com/mnemosyne-proj/mnemosyne/issues/278

I manually checked the contents of every file in the project and removed the execution flag from everything that was not supposed to be run directly.
```diff
-Manual verification was tedious, make sure I did everything correctly.
```

I doubt this pull request should be accepted. It can be rejected and left as a reminder that many files have excessive execution rights.

And in the future, never set file permissions recursively :)

### CODE REVIEW

**Comment by blogdron** [comment]
Hmmm, why after change flags, files shows as emply? Close now. Im dont understand it

**Comment by blogdron** [comment]
>Hmmm, why after change flags, files shows as emply? Close now. Im dont understand it

It's just a github feature

**Comment by pbienst** [comment]
Do you want me to merge this now or not?

**Comment by blogdron** [comment]
Аt your discretion.

**Comment by kuraga** [comment]
Thanks!

**Pull request merged**
