### PR TITLE
[RDY] Debug 3.5 failures on Windows.

### PR DESCRIPTION
**Pull request by three-comrades**
~~Work in progress.~~ Ready.

### CODE REVIEW

**Comment by pbienst** [comment]
I'm a bit new to the git workflow. This showed up as a pull request, but it still seems work in progress and has conflicts?

**Comment by three-comrades** [comment]
Yes, it's still work in progress (i.e., don't merge yet). I had to post it early, so appveyor runs the windows tests and I can try and debug the hang.

As for the git workflow: there are many ways to handle things. Personally, if there are merge conflics, I would ask the submitter to rebase on the master branch. That way, the submitter (who knows his changes best) has to resolve merge conflicts and it is easier to review for you, because the result will be a new set of incremental changes on top of the current master branch.

Btw, it seems to me you are working in your personal fork on the master branch. You can totally do that, but branching in git is so cheap that most people create a branch for whatever feature they are currently working on (`git checkout -b <branch name>`). If you add commits to the master branch in your personal fork it makes it harder to get changes from the upstream master branch.

My personal rule is: never touch the local master branch. That way, it is super easy to get the newest upstream changes:
```
git checkout master
git fetch upstream
git merge upstream/master
```
If I didn't do any changes to my local master branch, `git merge upstream/master` doesn't even result in a merge commit; it does a fast-forward merge.

git comes with a GUI that was invaluable to me in the beginning for its visualization: `gitk --all` (visualizes all branches).

**Comment by pbienst** [comment]
>Yes, it's still work in progress (i.e., don't merge yet). I had to post it early, so appveyor runs the windows tests and I can try and debug the hang.

But does everything you post result in a merge request? Or was the merge request created by accident?

>My personal rule is: never touch the local master branch. That way, it is super easy to get the newest upstream changes:

OK, will do.



>git checkout master

>git fetch upstream

>git merge upstream/master

Would ‘git pull upstream master’ work just as well? From https://www.atlassian.com/git/tutorials/comparing-workflows/forking-workflow

Still getting my head around this git thing ☺

**Comment by three-comrades** [comment]
> But does everything you post result in a merge request? Or was the merge request created by accident?

I'm not quite sure I understand what you mean. I can push to my personal fork on Github without you automatically noticing. I have to explictly open a pull request. In this special case I opened the pull request before the changes are final/ready, because the windows build bot doesn't track my personal repository, but they track any opened pull requests to the official repository - which I need here, because I'm explicitly trying to fix a hang on the build bot and without the tracking I can't test my stuff.

> Would ‘git pull upstream master’ work just as well? From https://www.atlassian.com/git/tutorials/comparing-workflows/forking-workflow

If you don't have any additional changes in your local master branch that would work as well (and even if you do, it probably would). `git pull` fetches and merges in one step. I prefer to keep the steps separate, because it gives me a chance to have a look at what I'm about to merge and it feels less magical. But in this Github setup here it doesn't really matter. There are long arguments on the internet about which is better, but with the rule of not touching local master `git pull upstream master` should work perfectly well and not give surprising results.

**Comment by three-comrades** [comment]
The things you learn .... I found the first problem:

- line endings:  When you check a file out/clone a repository git can change the line endings to the standard on your plattform. On Windows that's '\r\n'. When you commit a file, git automatically changes the line endings to whatever is actually stored in git. That's all nice, but if you have binary files that git doesn't automatically detect as a binary file (like pickled files) you run into troubles. 
When converting menmosyne to git, I didn't tell it to handle `*.mem` files in the test suite as binary files, which resulted in git changing the line endings to `\r\n`, which resulted in `pickle.load(open('foo.mem', 'rb'), encoding='bytes')` chocking on said line endings. 

So, the last commit adds a `.gitattributes` file that tells git to handle `*.mem` files as binary.

Are there any other text like files that should be handled as binary?

**Comment by pbienst** [comment]
Good catch! From memory, the main candidates for binary files are with extensions png, db, mem, anki snd apkg, most of them in the test/files directory. There's also the Android Python binaries.

**Comment by three-comrades** [comment]
[These](https://gist.github.com/three-comrades/4d5fe75fb35df6d15d6e8490ec9ac4fb) are all files git now handles as binary. Looks like it detected all the files you mentioned automatically, so we should be good.

Regarding the rest of the test failures on Python 3.5 on Windows: I could replicate them on my machine but I have no idea what's going on. All test failures seem to be because of sqlite suddenly not being able to open the database file (`sqlite3.OperationalError: unable to open database file`) and if that error occurs in a thread then that causes nose to hang, it seems.

If you rename one of the failing tests to `test_a`, or delete all other test cases from the file, so that the failing test is run first in the test file, then the error goes away for that test case. I don't know much about sqlite, so I'm at a loss here. I thought it may have to do with the number of open connections (but if I understand the code correctly there's only one) or some garbage collection details, but I'm just poking around in the dark ... It's just weird that it doesn't occur with Python 3.6.

If you don't have any more ideas I will clean this up and we can merge the useful parts. And then I just hope that the failures don't point to a real problem ¯\\\_(ツ)\_/¯

**Comment by pbienst** [comment]
I suspect these are due to the tests in test_sync.py not being totally threadsafe. I wouldn't worry about it too much, especially since it works with 3.6, the version used to build the binaries.

Just let me know when you want me to merge this. (or feel free to do it yourself)

**Comment by three-comrades** [comment]
I found the reason (see last commit), but I don't know what it means.

The pragma `temp_store_directory` is [deprecated](https://sqlite.org/pragma.html#pragma_temp_store_directory) and on the mailing list they talk about using a [`TEMP` environment variable](http://sqlite.1065341.n5.nabble.com/pragma-temp-store-directory-is-deprecated-what-is-the-alternative-td83280.html). It is specifically not thread-safe, but the inital failing test was `test_logging.py` and as far as I can see it doesn't even use different threads (or maybe `nose` does in the background?).

So, ignore? :)

**Comment by pbienst** [comment]
The pragma is needed for the Android implementation as the comment says, so I wouldn't remove it for the sake of making the testsuite pass on an old Python version...

**Comment by three-comrades** [comment]
Makes sense.

Okay, I cleaned everything up and this should be the resulting set of useful changes from the whole endeavour.
I extended one test case a bit to cover the changed exception handling; maybe you have a quick look to see if you like it.
Otherwise this is ready to merge.

**Pull request merged**
