### PR TITLE
Android rework

### PR DESCRIPTION
**Pull request by three-comrades**
I rebased the branch on master, and added a commit on top that fixes the git instructions.

I had two merge conflicts, that I resolved like the following (diff compared to the original branch before rebasing):

```diff
diff --git a/mnemosyne/libmnemosyne/__init__.py b/mnemosyne/libmnemosyne/__init__.py
index 5ba95a20..a6d9aeb5 100644
--- a/mnemosyne/libmnemosyne/__init__.py
+++ b/mnemosyne/libmnemosyne/__init__.py
@@ -154,6 +154,10 @@ class Mnemosyne(Component):
           "CuecardWcu")]
         self.gui_for_component = {}
 
+    def android_log(self, message):
+        if hasattr(self, "android"):
+            self.android.Log("Mnemosyne", message)
+
     def handle_exception(self, type, value, tb):
         body = "An unexpected error has occurred.\n" + \
             "Please forward the following info to the developers:\n\n" + \
@@ -161,6 +165,7 @@ class Mnemosyne(Component):
         list = traceback.format_tb(tb, limit=None) + \
                traceback.format_exception_only(type, value)
         body = body + "%-20s %s" % ("".join(list[:-1]), list[-1])
+        self.android_log(body)
         print("Log body", body)
         try:
             if sys.platform != "win32":
@@ -178,6 +183,8 @@ class Mnemosyne(Component):
 
         """
 
+        if hasattr(self, "android"):
+            self.component_manager.android = self.android
         if debug_file:
             self.component_manager.debug_file = open(debug_file, "w")
         self.register_components()
@@ -264,6 +271,8 @@ class Mnemosyne(Component):
 
         """
 
+        # Help with debugging under Android.
+        self.component_manager.android_log = self.android_log
         # Activate config and inject necessary settings.
         try:
             self.component_manager.current("config").activate()
@@ -335,6 +344,7 @@ class Mnemosyne(Component):
                 self.database().load(path)
             self.controller().update_title()
         except RuntimeError as e:
+            self.android_log(str(e))
             self.main_widget().show_error(str(e))
             from mnemosyne.libmnemosyne.translator import _
             self.main_widget().show_information(\
diff --git a/mnemosyne/libmnemosyne/configuration.py b/mnemosyne/libmnemosyne/configuration.py
index c785a637..6bdfba22 100644
--- a/mnemosyne/libmnemosyne/configuration.py
+++ b/mnemosyne/libmnemosyne/configuration.py
@@ -9,6 +9,7 @@ import time
 import sqlite3
 import threading
 import importlib
+import textwrap
 
 from mnemosyne.libmnemosyne.translator import _
 from mnemosyne.libmnemosyne.component import Component
@@ -20,60 +21,70 @@ DAY = 24 * HOUR # Seconds in a day.
 
 re_long_int = re.compile(r"\d+L")
 
-
-config_py = \
-"""# Mnemosyne configuration file.
-
-# This file contains settings which we deem to be too specialised to be
-# accesible from the GUI. However, if you use some of these settings, feel
-# free to inform the developers so that it can be re-evaluated if these
-# settings need to be exposed in the GUI.
-
-# Science server. Only change when prompted by the developers.
-science_server = "mnemosyne-proj.dyndns.org:80"
-
-# Set to True to prevent you from accidentally revealing the answer when
-# clicking the edit button.
-only_editable_when_answer_shown = False
-
-# Set to False if you don't want the tag names to be shown in the review
-# window.
-show_tags_during_review = True
-
-# The number of daily backups to keep. Set to -1 for no limit.
-max_backups = 10
-
-# Start the card browser with the last used colum sort. Can have a serious
-# performance penalty for large databases.
-start_card_browser_sorted = False
-
-# The moment the new day starts. Defaults to 3 am. Could be useful to change
-# if you are a night bird. You can only set the hours, not minutes, and
-# midnight corresponds to 0.
-day_starts_at = 3
-
-# On mobile clients with slow SD cards copying a large database for the backup
-# before sync can take longer than the sync itself, so we offer reckless users
-# the possibility to skip this.
-backup_before_sync = True
-
-# Latex preamble. Note that for the pre- and postamble you need to use double
-# slashes instead of single slashes here, to have them escaped when Python
-# reads them in.
-latex_preamble = r\"\"\"
-\documentclass[12pt]{article}
-\pagestyle{empty}
-\\begin{document}\"\"\"
-
-# Latex postamble.
-latex_postamble = r\"\"\"\end{document}\"\"\"
-
-# Latex command.
-latex = "latex -interaction=nonstopmode"
-
-# Latex dvipng command.
-dvipng = "dvipng -D 200 -T tight tmp.dvi"
-"""
+def config_py():
+  config_py = textwrap.dedent(
+  """  # Mnemosyne configuration file.
+
+  # This file contains settings which we deem to be too specialised to be
+  # accesible from the GUI. However, if you use some of these settings, feel
+  # free to inform the developers so that it can be re-evaluated if these
+  # settings need to be exposed in the GUI.
+
+  # Science server. Only change when prompted by the developers.
+  science_server = "mnemosyne-proj.dyndns.org:80"
+
+  # Set to True to prevent you from accidentally revealing the answer when
+  # clicking the edit button.
+  only_editable_when_answer_shown = False
+
+  # Set to False if you don't want the tag names to be shown in the review
+  # window.
+  show_tags_during_review = True
+
+  # The number of daily backups to keep. Set to -1 for no limit.
+  max_backups = 10
+
+  # Start the card browser with the last used colum sort. Can have a serious
+  # performance penalty for large databases.
+  start_card_browser_sorted = False
+
+  # The moment the new day starts. Defaults to 3 am. Could be useful to change
+  # if you are a night bird. You can only set the hours, not minutes, and
+  # midnight corresponds to 0.
+  day_starts_at = 3
+
+  # On mobile clients with slow SD cards copying a large database for the backup
+  # before sync can take longer than the sync itself, so we offer reckless users
+  # the possibility to skip this.
+  backup_before_sync = True
+
+  # Latex preamble. Note that for the pre- and postamble you need to use double
+  # slashes instead of single slashes here, to have them escaped when Python
+  # reads them in.
+  latex_preamble = r\"\"\"
+  \documentclass[12pt]{article}
+  \pagestyle{empty}
+  \\begin{document}\"\"\"
+
+  # Latex postamble.
+  latex_postamble = r\"\"\"\end{document}\"\"\"
+
+  # Latex command.
+  latex = "latex -interaction=nonstopmode"
+
+  # Latex dvipng command.
+  dvipng = "dvipng -D 200 -T tight tmp.dvi"
+  """)
+
+  if sys.platform == "darwin":
+    # We could use format strings, but the LaTeX has too many { } characters
+    config_py = config_py.replace(
+        'latex = "latex -interaction=nonstopmode"',
+        'latex = "/Library/TeX/texbin/latex -output-format=dvi -interactiononstopmode"')
+    config_py = config_py.replace(
+        'dvipng = "dvipng -D 200 -T tight tmp.dvi"',
+        'dvipng = "/Library/TeX/texbin/dvipng -D 200 -T tight tmp.dvi"')
+  return config_py
 
 class Configuration(Component, dict):
 
@@ -322,7 +333,7 @@ class Configuration(Component, dict):
         config_file = join(self.config_dir, "config.py")
         if not exists(config_file):
             f = open(config_file, "w")
-            print(config_py, file=f)
+            print(config_py(), file=f)
             f.close()
         # Create machine_id. Do this in a separate file, as extra warning
         # signal that people should not copy this file to a different machine.
```

### CODE REVIEW

**Comment by pbienst** [comment]
Thanks! Actually, the first conflict should be resolved the other way, i.e. getting rid of the debug statements in that location.
With the updated instructions, I'll give the branch per feature workflow another go :-)

**Comment by three-comrades** [comment]
Okay, I swapped that one merge conflict. But merging the other PR introduced more merge conflicts:
```diff
diff --cc mnemosyne/android/app/src/main/AndroidManifest.xml
index 1db65e50,8f6839ef..00000000
--- a/mnemosyne/android/app/src/main/AndroidManifest.xml
+++ b/mnemosyne/android/app/src/main/AndroidManifest.xml
@@@ -2,7 -2,7 +2,11 @@@
  <manifest xmlns:android="http://schemas.android.com/apk/res/android"
      package="org.mnemosyne"
      android:versionCode="25"
++<<<<<<< HEAD
+    android:versionName="1.6" >
++=======
+     android:versionName="2.0" >
++>>>>>>> android-rework
```
-> resolved to 2.0

```diff
diff --cc mnemosyne/android/app/src/main/AndroidManifest.xml
index 1db65e50,8f6839ef..00000000
--- a/mnemosyne/android/app/src/main/AndroidManifest.xml
+++ b/mnemosyne/android/app/src/main/AndroidManifest.xml
@@@ -2,7 -2,7 +2,11 @@@
  <manifest xmlns:android="http://schemas.android.com/apk/res/android"
      package="org.mnemosyne"
      android:versionCode="25"
    android:versionName="1.6" >
      </option>
    </component>
++<<<<<<< HEAD
+  <component name="ProjectRootManager" version="2" languageLevel="JDK_1_8" default="true" project-jdk-name="1.8" project-jdk-type="JavaSDK">
++=======
+   <component name="ProjectRootManager" version="2" languageLevel="JDK_1_7" default="true" project-jdk-name="1.8" project-jdk-type="JavaSDK">
++>>>>>>> android-rework
```
Resolved to `languageLevel="JDK_1_7"`, because that came from the `android-rework` branch ...

**Comment by three-comrades** [comment]
Btw, is this supposed to go into a 2.6.1 maintenance release, or is this work for a 2.7 release? If the latter, we need to make sure to merge 2.6.x fixes on a separate 2.6 branch after this got merged.

**Comment by pbienst** [comment]
Ok!


________________________________

**Comment by pbienst** [comment]
This is for 2.6.1.


________________________________

**Pull request merged**
