### PR TITLE
Completed czech .po translations

### PR DESCRIPTION
**Pull request by ioma8**
I have finished the czech translations.

### CODE REVIEW

**Comment by pbienst** [comment]
Much appreciated, thanks!

**Comment by ioma8** [comment]
@pbienst Np. :) I am also python dev, if there is any help you could use on this project, let me know.

**Comment by pbienst** [comment]
Basically, if there's any of your own Mnemosyne itches that you'd like to scratch, that's probably the best place to start :-)

**Comment by ioma8** [comment]
@pbienst yea I found there is not all strings in po files so I will start by fixing the missing gettexts in sources. :)

**Comment by pbienst** [comment]
Sounds good! (Note that the strings that belong to the Qt library itself need a different translation mechanism, which is not implemented yet.)

**Pull request merged**
